---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample1
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - ../../overrides/bootstrap/global-infra.yaml
    path: charts/oneaoa
    repoURL: https://github.com/cbsi-cbscom/pplus-lsp-argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true