---
# Source: test-aoa/templates/apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-App
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - ../../overrides/sample-aoa.yaml
    path: charts/test-chart
    repoURL: https://github.com/cbsi-cbscom/pplus-lsp-argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true